version: 0.1

phases:
  build:
    commands:
      - echo Entered the build phase...
      - mvn clean package
  post_build:
    commands:
      - echo Build completed successfully
artifacts:
  files:
    - target/aws-elasticbeanstalk-example-0.0.1-SNAPSHOT.war
  discard-paths: yes